import {Link,useNavigate} from 'react-router-dom';import {Minus,Plus,ShoppingCart,Search,MapPin,ChevronRight,Home,LayoutGrid,UserRound} from 'lucide-react';import {motion,AnimatePresence} from 'framer-motion';import {useApp} from '../context/AppContext';import {products} from '../data/products';
export const money=n=>`₹${n}`;
export function Quantity({product}){const {qty,setQty}=useApp();const n=qty(product.id);return n?<motion.div initial={{scale:.8}} animate={{scale:1}} className="flex h-8 items-center justify-between rounded-md bg-brand px-1 text-sm font-bold text-white"><button aria-label="decrease" onClick={()=>setQty(product.id,n-1)}><Minus size={15}/></button><span>{n}</span><button aria-label="increase" onClick={()=>setQty(product.id,n+1)}><Plus size={15}/></button></motion.div>:<button onClick={()=>setQty(product.id,1)} className="h-8 w-full rounded-md border border-brand bg-[#f7fff8] text-sm font-bold text-brand">ADD</button>}
export function ProductCard({product}){return <Link to={`/product/${product.id}`} className="block min-w-[142px] rounded-xl border border-gray-100 bg-white p-2 card-shadow"><img src={product.image} className="h-24 w-full rounded-lg object-cover"/><p className="mt-2 h-9 overflow-hidden text-xs font-semibold leading-4">{product.name}</p><p className="mt-1 text-[11px] text-gray-500">{product.unit}</p><div className="mt-2 flex items-end gap-1"><b className="text-sm">{money(product.price)}</b><s className="text-[10px] text-gray-400">{money(product.mrp)}</s></div><div className="mt-2" onClick={e=>e.preventDefault()}><Quantity product={product}/></div></Link>}
export function Header(){const {state}=useApp();const nav=useNavigate();return <header className="sticky top-0 z-20 border-b bg-white"><div className="flex items-center justify-between px-4 py-3"><button onClick={()=>nav('/address')} className="text-left"><b className="block text-lg leading-5">Delivery in 8 minutes <span className="text-brand">⌄</span></b><span className="flex max-w-[250px] items-center gap-1 truncate text-xs"><MapPin size={12}/>{state.address?.line1||'Choose your location'}</span></button><button onClick={()=>nav('/cart')} className="relative rounded-lg bg-[#f1f8ef] p-2"><ShoppingCart size={22}/>{state.cart.length>0&&<i className="absolute -right-1 -top-1 flex h-4 w-4 items-center justify-center rounded-full bg-brand text-[10px] not-italic text-white">{state.cart.length}</i>}</button></div><button onClick={()=>nav('/search')} className="mx-3 mb-3 flex w-[calc(100%-24px)] items-center gap-2 rounded-xl border bg-gray-50 px-3 py-3 text-left text-sm text-gray-500"><Search size={18}/>Search for atta, dal, cold drinks...</button></header>}
export function CartBar(){const {state}=useApp();const total=state.cart.reduce((x,i)=>x+(products.find(p=>p.id===i.productId)?.price||0)*i.quantity,0);const count=state.cart.reduce((x,i)=>x+i.quantity,0);return <AnimatePresence>{count>0&&<motion.div initial={{y:90}} animate={{y:0}} exit={{y:90}} className="fixed bottom-16 z-30 w-full max-w-[430px] px-3"><Link to="/cart" className="flex items-center justify-between rounded-xl bg-brand px-4 py-3 text-white shadow-xl"><span><b>{count} item{count>1?'s':''}</b><small className="ml-2">{money(total)}</small></span><b className="flex items-center gap-1">View Cart <ChevronRight size={17}/></b></Link></motion.div>}</AnimatePresence>}
export function BottomNav(){return <nav className="fixed bottom-0 z-20 flex h-16 w-full max-w-[430px] justify-around border-t bg-white pt-2 text-[10px]"><Link to="/" className="flex flex-col items-center gap-1"><Home size={21}/>Home</Link><Link to="/categories" className="flex flex-col items-center gap-1"><LayoutGrid size={21}/>Categories</Link><Link to="/cart" className="flex flex-col items-center gap-1"><ShoppingCart size={21}/>Cart</Link><Link to="/account" className="flex flex-col items-center gap-1"><UserRound size={21}/>Account</Link></nav>}
export function Page({children,nav=true}){return <motion.main initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0}} transition={{duration:.18}} className={nav?'safe-bottom':''}>{children}{nav&&<><CartBar/><BottomNav/></>}</motion.main>}
export function Back({title}){const n=useNavigate();return <div className="flex items-center gap-3 border-b px-4 py-4"><button onClick={()=>n(-1)} className="text-2xl">‹</button><h1 className="font-bold">{title}</h1></div>}
